# Project-wide Gradle settings.

# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the command line, check
# http://developer.android.com/tools/revisions/gradle-dsl.html for more details.

# The Gradle daemon aims to improve the build server performance by keeping processes around between builds.
# The prewarm setting disables prewarm which we don't use in CI environments
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.workers.max=4
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m -Djdk.lang.processReaperUseDefaultStackSize=true
android.jetifier.ignorelist=react-android
android.enableJetifier=true
android.useAndroidX=true

# Hermes and New Architecture
hermesEnabled=true
newArchEnabled=false

# Use Android Studio's bundled JDK instead of System's Java 21 to avoid Android build failures
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr
